# src/RAbot/llm/research_writer.py

from __future__ import annotations

from typing import Any

import pandas as pd

from RAbot.analysis.indicators import (
    add_technical_indicators,
    build_asset_performance_table,
)
from RAbot.analysis.macro_research import (
    build_asset_macro_research,
    build_macro_indicator_snapshot,
)
from RAbot.analysis.news_research import (
    build_asset_news_research,
    build_news_market_snapshot,
)
from RAbot.analysis.research_engine import (
    build_market_overview,
    build_single_asset_research,
)
from RAbot.llm.llm_client import LLMResult, RAbotLLMClient
from RAbot.llm.research_prompt import (
    SYSTEM_PROMPT_RESEARCH_ANALYST,
    build_asset_analyst_prompt,
    build_market_analyst_prompt,
)


class RAbotResearchWriter:
    """
    LLM-powered research analyst.

    This layer does not fetch external data by itself. It only receives
    structured facts generated by RAbot, then asks the LLM to identify
    main conflicts, supporting evidence, uncertainty, hypotheses and watch variables.
    """

    def __init__(self, client: RAbotLLMClient | None = None) -> None:
        self.client = client or RAbotLLMClient()

    def generate_market_observation(
        self,
        all_data: pd.DataFrame,
        all_news: pd.DataFrame,
        all_macro: pd.DataFrame,
        focus_assets: list[str] | None = None,
    ) -> LLMResult:
        context = build_market_research_context(
            all_data=all_data,
            all_news=all_news,
            all_macro=all_macro,
            focus_assets=focus_assets,
        )

        user_prompt = build_market_analyst_prompt(context)

        return self.client.generate(
            system_prompt=SYSTEM_PROMPT_RESEARCH_ANALYST,
            user_prompt=user_prompt,
        )

    def generate_asset_observation(
        self,
        all_data: pd.DataFrame,
        all_news: pd.DataFrame,
        all_macro: pd.DataFrame,
        asset_symbol: str,
    ) -> LLMResult:
        context = build_asset_research_context(
            all_data=all_data,
            all_news=all_news,
            all_macro=all_macro,
            asset_symbol=asset_symbol,
        )

        user_prompt = build_asset_analyst_prompt(context)

        return self.client.generate(
            system_prompt=SYSTEM_PROMPT_RESEARCH_ANALYST,
            user_prompt=user_prompt,
        )


def build_market_research_context(
    all_data: pd.DataFrame,
    all_news: pd.DataFrame,
    all_macro: pd.DataFrame,
    focus_assets: list[str] | None = None,
) -> dict[str, Any]:
    focus_assets = focus_assets or [
        "NASDAQ",
        "SP500",
        "CSI300",
        "SSE",
        "HSI",
        "GOLD",
        "DXY",
        "WTI",
        "VIX",
    ]

    context: dict[str, Any] = {
        "scope": "global_market",
        "instruction": (
            "This is a structured fact package generated by RAbot. "
            "The analyst must reason only from these facts."
        ),
        "data_status": {},
        "market_overview": {},
        "asset_performance": [],
        "macro_snapshot": [],
        "news_snapshot": {},
        "top_news": [],
        "focus_asset_rule_outputs": [],
    }

    if all_data is None or all_data.empty:
        context["data_status"]["market_data"] = "empty"
        return context

    data = all_data.copy()

    if "date" in data.columns:
        data["date"] = pd.to_datetime(data["date"], errors="coerce")

    context["data_status"]["market_data"] = {
        "asset_count": int(data["symbol"].nunique()) if "symbol" in data.columns else 0,
        "row_count": int(len(data)),
        "min_date": _fmt_date(data["date"].min()) if "date" in data.columns else "NA",
        "max_date": _fmt_date(data["date"].max()) if "date" in data.columns else "NA",
    }

    perf_df = _safe_call(lambda: build_asset_performance_table(data), default=pd.DataFrame())
    market_overview = _safe_call(lambda: build_market_overview(perf_df), default={})
    context["market_overview"] = _json_safe_dict(market_overview)

    if perf_df is not None and not perf_df.empty:
        perf_cols = [
            "symbol",
            "name",
            "近1周收益率%",
            "近1月收益率%",
            "近3月收益率%",
            "YTD收益率%",
            "近1年收益率%",
            "20日年化波动率%",
            "当前回撤%",
        ]
        show_cols = [c for c in perf_cols if c in perf_df.columns]
        sort_col = "近1月收益率%" if "近1月收益率%" in perf_df.columns else None

        perf_show = perf_df[show_cols].copy()

        if sort_col and sort_col in perf_show.columns:
            perf_show = perf_show.sort_values(
                sort_col,
                ascending=False,
                na_position="last",
            )

        context["asset_performance"] = _df_records(perf_show.head(20))

    macro_snapshot = _safe_call(
        lambda: build_macro_indicator_snapshot(all_macro),
        default=pd.DataFrame(),
    )

    if macro_snapshot is not None and not macro_snapshot.empty:
        macro_cols = [
            "symbol",
            "name",
            "region",
            "category",
            "frequency",
            "latest_date",
            "latest_value",
            "change_1m",
            "change_3m",
            "trend_label",
            "risk_label",
            "interpretation",
        ]
        show_cols = [c for c in macro_cols if c in macro_snapshot.columns]
        macro_show = macro_snapshot[show_cols].copy()
        context["macro_snapshot"] = _df_records(macro_show.head(30))

    news_snapshot = _safe_call(
        lambda: build_news_market_snapshot(all_news, days=7),
        default={},
    )
    context["news_snapshot"] = _json_safe_dict(news_snapshot)

    if all_news is not None and not all_news.empty:
        news = all_news.copy()

        if "quality_score" in news.columns:
            news["quality_score"] = pd.to_numeric(news["quality_score"], errors="coerce")
            news = news.sort_values(
                "quality_score",
                ascending=False,
                na_position="last",
            )
        elif "importance_score" in news.columns:
            news["importance_score"] = pd.to_numeric(news["importance_score"], errors="coerce")
            news = news.sort_values(
                "importance_score",
                ascending=False,
                na_position="last",
            )

        news_cols = [
            "published_at",
            "source_name",
            "title",
            "event_type",
            "source_tier",
            "quality_score",
            "sentiment_label",
            "importance_score",
            "related_assets",
            "interpretation",
        ]
        show_cols = [c for c in news_cols if c in news.columns]
        context["top_news"] = _df_records(news[show_cols].head(12))

    available_assets = (
        set(data["symbol"].dropna().astype(str).tolist())
        if "symbol" in data.columns
        else set()
    )

    for asset in focus_assets:
        if asset not in available_assets:
            continue

        asset_context = build_asset_research_context(
            all_data=data,
            all_news=all_news,
            all_macro=all_macro,
            asset_symbol=asset,
            compact=True,
        )
        context["focus_asset_rule_outputs"].append(asset_context)

    return _json_safe_dict(context)


def build_asset_research_context(
    all_data: pd.DataFrame,
    all_news: pd.DataFrame,
    all_macro: pd.DataFrame,
    asset_symbol: str,
    compact: bool = False,
) -> dict[str, Any]:
    asset = str(asset_symbol).upper().strip()

    context: dict[str, Any] = {
        "scope": "single_asset",
        "asset_symbol": asset,
        "instruction": (
            "This is a structured fact package generated by RAbot. "
            "The analyst must reason only from these facts."
        ),
        "data_status": {},
        "asset_name": asset,
        "price_facts": {},
        "technical_rule_output": {},
        "news_rule_output": {},
        "macro_rule_output": {},
        "recent_technical_table": [],
        "related_news": [],
        "related_macro_indicators": [],
    }

    if all_data is None or all_data.empty or "symbol" not in all_data.columns:
        context["data_status"]["asset_data"] = "empty"
        return context

    df = all_data[all_data["symbol"] == asset].copy()

    if df.empty:
        context["data_status"]["asset_data"] = "not_found"
        return context

    if "date" in df.columns:
        df["date"] = pd.to_datetime(df["date"], errors="coerce")
        df = df.sort_values("date")

    name = asset
    if "name" in df.columns and not df["name"].dropna().empty:
        name = df["name"].dropna().astype(str).iloc[-1]

    context["asset_name"] = name
    context["data_status"]["asset_data"] = {
        "row_count": int(len(df)),
        "min_date": _fmt_date(df["date"].min()) if "date" in df.columns else "NA",
        "max_date": _fmt_date(df["date"].max()) if "date" in df.columns else "NA",
    }

    tech_df = _safe_call(lambda: add_technical_indicators(df), default=df)

    if tech_df is not None and not tech_df.empty:
        latest = tech_df.iloc[-1].to_dict()
    else:
        latest = {}

    price_fields = [
        "date",
        "close",
        "pct_change",
        "ma20",
        "ma60",
        "ma120",
        "volatility_20d",
        "drawdown",
        "volume",
    ]

    context["price_facts"] = {
        k: _json_safe_value(latest.get(k))
        for k in price_fields
        if k in latest
    }

    technical = _safe_call(
        lambda: build_single_asset_research(df),
        default={},
    )
    context["technical_rule_output"] = _json_safe_dict(technical)

    asset_news = _safe_call(
        lambda: build_asset_news_research(
            all_news,
            asset_symbol=asset,
            technical_score=technical.get("score") if isinstance(technical, dict) else None,
            days=7,
        ),
        default={},
    )
    context["news_rule_output"] = _compact_news_output(asset_news)

    asset_macro = _safe_call(
        lambda: build_asset_macro_research(
            all_macro,
            asset_symbol=asset,
            technical_score=technical.get("score") if isinstance(technical, dict) else None,
        ),
        default={},
    )
    context["macro_rule_output"] = _compact_macro_output(asset_macro)

    if not compact:
        recent_cols = [
            "date",
            "close",
            "pct_change",
            "ma20",
            "ma60",
            "ma120",
            "volatility_20d",
            "drawdown",
        ]
        if tech_df is not None and not tech_df.empty:
            show_cols = [c for c in recent_cols if c in tech_df.columns]
            if show_cols:
                context["recent_technical_table"] = _df_records(
                    tech_df[show_cols].tail(12)
                )

        related_news_df = (
            asset_news.get("data", pd.DataFrame())
            if isinstance(asset_news, dict)
            else pd.DataFrame()
        )
        if related_news_df is not None and not related_news_df.empty:
            news_cols = [
                "published_at",
                "source_name",
                "title",
                "event_type",
                "source_tier",
                "quality_score",
                "sentiment_label",
                "importance_score",
                "related_assets",
                "interpretation",
            ]
            show_cols = [c for c in news_cols if c in related_news_df.columns]
            if show_cols:
                context["related_news"] = _df_records(
                    related_news_df[show_cols].head(10)
                )

        macro_indicators = (
            asset_macro.get("top_indicators", pd.DataFrame())
            if isinstance(asset_macro, dict)
            else pd.DataFrame()
        )
        if macro_indicators is not None and not macro_indicators.empty:
            macro_cols = [
                "symbol",
                "name",
                "region",
                "category",
                "frequency",
                "latest_date",
                "latest_value",
                "change_1m",
                "change_3m",
                "trend_label",
                "risk_label",
                "asset_effect_score",
                "interpretation",
            ]
            show_cols = [c for c in macro_cols if c in macro_indicators.columns]
            if show_cols:
                context["related_macro_indicators"] = _df_records(
                    macro_indicators[show_cols].head(12)
                )

    return _json_safe_dict(context)


def _compact_news_output(asset_news: dict[str, Any]) -> dict[str, Any]:
    if not isinstance(asset_news, dict):
        return {}

    keys = [
        "total_news",
        "high_importance_count",
        "bullish_count",
        "bearish_count",
        "neutral_count",
        "avg_importance",
        "news_bias",
        "alignment_label",
        "summary",
        "risk_points",
        "support_points",
        "top_news",
    ]

    return {
        k: _json_safe_value(asset_news.get(k))
        for k in keys
        if k in asset_news
    }


def _compact_macro_output(asset_macro: dict[str, Any]) -> dict[str, Any]:
    if not isinstance(asset_macro, dict):
        return {}

    keys = [
        "summary",
        "support_points",
        "risk_points",
        "neutral_points",
        "macro_bias",
        "macro_score",
        "alignment_label",
    ]

    return {
        k: _json_safe_value(asset_macro.get(k))
        for k in keys
        if k in asset_macro
    }


def _df_records(df: pd.DataFrame) -> list[dict[str, Any]]:
    if df is None or df.empty:
        return []

    clean = df.copy()

    for col in clean.columns:
        if pd.api.types.is_datetime64_any_dtype(clean[col]):
            clean[col] = clean[col].dt.strftime("%Y-%m-%d")

    records = clean.to_dict(orient="records")
    return [_json_safe_dict(x) for x in records]


def _json_safe_dict(obj: Any) -> Any:
    if isinstance(obj, dict):
        return {str(k): _json_safe_dict(v) for k, v in obj.items()}

    if isinstance(obj, list):
        return [_json_safe_dict(x) for x in obj]

    if isinstance(obj, tuple):
        return [_json_safe_dict(x) for x in obj]

    return _json_safe_value(obj)


def _json_safe_value(value: Any) -> Any:
    if isinstance(value, pd.DataFrame):
        return _df_records(value)

    if isinstance(value, pd.Series):
        return _json_safe_dict(value.to_dict())

    if isinstance(value, pd.Timestamp):
        return value.strftime("%Y-%m-%d")

    if isinstance(value, (list, dict, tuple, set)):
        return _json_safe_dict(list(value)) if isinstance(value, (set, tuple)) else _json_safe_dict(value)

    try:
        if pd.isna(value):
            return None
    except Exception:
        pass

    try:
        import numpy as np

        if isinstance(value, np.integer):
            return int(value)

        if isinstance(value, np.floating):
            return float(value)

        if isinstance(value, np.bool_):
            return bool(value)
    except Exception:
        pass

    return value


def _fmt_date(value: Any) -> str:
    dt = pd.to_datetime(value, errors="coerce")
    if pd.isna(dt):
        return "NA"
    return dt.strftime("%Y-%m-%d")


def _safe_call(func, default):
    try:
        return func()
    except Exception:
        return default